server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: authservice
          uri: http://ec2-3-216-146-132.compute-1.amazonaws.com:8080
          predicates:
            - Path=/api/v1/**
        - id: UserProfile
          uri: http://ec2-3-216-146-132.compute-1.amazonaws.com:8081
          predicates:
            - Path=/api/v2/**
        - id: MovieList
          uri: http://ec2-3-216-146-132.compute-1.amazonaws.com:8082
          predicates:
            -  Path=/api/v3/**
        - id: WishList
          uri: http://ec2-3-216-146-132.compute-1.amazonaws.com:8083
          predicates:
            - Path=/api/v4/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Controller-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
